### ISSUE TITLE
Retroalimentacion Clon de google

### ISSUE THREAD

**Issue by Guirdo** [Duarte8a/Google-Clone#1]
Para el código de CSS te recomiendo escribir las propiedades en una linea cada una para que sea fácil de leer, por ejemplo:

```css
header{
  display: flex; 
  justify-content: end; 
  height: 60px; 
  padding: 0 12px;
}
```
